### ISSUE TITLE
代码免费看，视频却要收费

### ISSUE THREAD

**Issue by HermanHwang** [roncoo/spring-boot-demo#3]

**Comment by tanpengsccd** [comment]
感觉star 是刷的

**Comment by HermanHwang** [comment]
我上面发的那些，一发出来讨论就被关了，

**Comment by tanpengsccd** [comment]
1k多星。就2个issues。一看就知道有问题。

Herman Huang <notifications@github.com>于2018年7月10日 周二下午8:45写道：

**Comment by HermanHwang** [comment]
github 居然被龙果学院  成功用于商业化了。。。

**Comment by tanpengsccd** [comment]
淘宝有刷星的服务。所以也不奇怪

Herman Huang <notifications@github.com>于2018年7月10日 周二下午8:57写道：
